// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var source = new EventSource("url");

function onOpenHandler(e) {
  console.log("EventSource opened", e);
  return /* () */0;
}

source.onopen = onOpenHandler;

function onMessageHandler(m) {
  console.log("EventSource message", m.data);
  return /* () */0;
}

source.onmessage = onMessageHandler;

exports.source           = source;
exports.onOpenHandler    = onOpenHandler;
exports.onMessageHandler = onMessageHandler;
/* source Not a pure module */
