// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var MessageEvent = /* module */[];

function readyStateToJs(param) {
  return param + 0 | 0;
}

function readyStateFromJs(param) {
  if (param <= 2 && 0 <= param) {
    return /* Some */[param - 0 | 0];
  } else {
    return /* None */0;
  }
}

exports.MessageEvent     = MessageEvent;
exports.readyStateToJs   = readyStateToJs;
exports.readyStateFromJs = readyStateFromJs;
/* No side effect */
